In [1]:
import numpy as np
np.__version__

'1.22.4'

In [2]:
import torch
torch.cuda.is_available()

True

In [1]:
from environment import PaperSoccer

In [2]:
game = PaperSoccer()

In [3]:
state = game.get_initial_state()
moves = game.get_valid_moves(state)
moves

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [5]:
enc = game.get_encoded_state(state)

In [6]:
enc.shape

(11, 9, 13)

In [23]:
state, player = game.get_next_state(state, 2, 1)
player

-1

In [16]:
state = game.change_perspective(state, -1)


In [10]:
game.print_history(state)


In [5]:
from mcts import MCTS

In [6]:
args = {
    'C': 1.41,
    'num_searches': 1000
}

bot = MCTS(game, args)

In [22]:
probs = bot.search(state)
bot_move = np.argmax(probs)
bot_move

2

In [12]:
moves

array([ True,  True,  True,  True, False,  True,  True,  True])

In [25]:
state, player = game.get_next_state(state, 6, 0)

In [26]:
game.printHistory(state)

036


In [14]:
state.connections

array([[[ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        