In [1]:
import numpy as np
np.__version__

'1.22.4'

In [2]:
import torch
torch.cuda.is_available()

True

In [2]:
from copy import deepcopy

In [19]:
def minPair(a, b):
    if(a[0] > b[0]):
        return (a, b)
    elif(a[0] < b[0]):
        return (b, a)
    elif(a[1] > b[1]):
        return (a, b)
    else:
        return (b, a)

class Board:
    def __init__(self, rows:int, columns:int):
        # rows x columns x 8 (8 directions)
        self.connections = np.array([[[True]*8]*columns]*rows)
        self.history = []
        self.playerX:int = rows//2
        self.playerY:int = columns//2
        self.visited = set((self.playerX, self.playerY))
        self.width:int = columns
        self.height:int = rows

    def move(self, direction):
        moves = [(0,1), (1,1), (1,0), (1,-1), (0,-1), (-1,-1), (-1,0), (-1,1)]
        changeX, changeY = moves[direction]
        prevX = self.playerX
        prevY = self.playerY
        self.playerX += changeX
        self.playerY += changeY
        self.connections[prevX][prevY][direction] = False
        self.connections[self.playerX][self.playerY][(direction+4)%8] = False
        if((self.playerX, self.playerY) in self.visited):
            return True
        else:
            self.visited.add((self.playerX, self.playerY))
            return False

class PaperSoccer:
    def __init__(self):
        self.rows = 13
        self.cols = 9
        self.action_size = 8

    def get_initial_state(self):
        return Board(self.rows, self.cols)
    
    def get_next_state(self, state:Board, action, player):
        state = deepcopy(state)
        state.history.append(action)
        repeat_player = state.move(action)
        if(repeat_player):
            return state, player
        else:
            return state, self.get_opponent(player)

    def get_valid_moves(self, state:Board):
        return state.connections[state.playerX][state.playerY]
    
    def get_value_and_terminated(self, state, action):
        if action == None:
            return 0, False
        state, player = self.get_next_state(state, action, 0)
        valid_moves = self.get_valid_moves(state)
        if(valid_moves.count(True) == 0):
            return -player, True
        else:
            if(state.playerY == 0):
                return 1, True
            elif(state.playerY == state.height-1):
                return -1, True
        return 0, False
    
    def get_opponent(self, player):
        return -player
    
    def get_opponent_value(self, value):
        return -value
    
    def change_perspective(self, state, player):
        return 
    
    def printHistory(self, state):
        for x in state.history:
            print(x, end="")
        print()
        

In [20]:
game = PaperSoccer()

In [21]:
state = game.get_initial_state()
moves = game.get_valid_moves(state)
moves

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [22]:
state, player = game.get_next_state(state, 0, 1)

In [18]:
game.printHistory(state)

0


In [27]:
moves = game.get_valid_moves(state)
moves

array([False,  True, False,  True,  True,  True,  True,  True])

In [12]:
moves

array([ True,  True,  True,  True, False,  True,  True,  True])

In [25]:
state, player = game.get_next_state(state, 6, 0)

In [26]:
game.printHistory(state)

036


In [14]:
state.connections

array([[[ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        